import {
  DesktopPC,
  DesktopPC1,
  DesktopPC2,
  DesktopPC3,
  Leptop,
  Leptop1,
  Leptop2,
  Monitor,
  Keyboard,
  Printer,
  VGA,
  VGA1,
  MotherBoard,
} from "../assets/page";

export const dataCard = [
  {
    id: 1,
    title: "Desktop PC",
    Subtitle: "Intel Mini Desktop  NUC i3-6100U BOXNUC6I3SYH",
    desc: "Intel Core i3-6100U, 4GB DDR4L, 500GB HDD, VGA Intel HD 520, GBe NIC, Wifi, Bluetooth, Win 10",
    price: 6875000,
    pic: DesktopPC,
  },
  {
    id: 2,
    title: "Desktop PC",
    Subtitle: "HP Desktop PC 110-050l H5Y71AA",
    desc: "Spesifikasi Detail Produk HP 110-050l Desktop Platfrom Desktop PC Processor Intel® Core™ i3-3240T Processor (2.9 GHz, Cache 3MB) Chipset Intel H61 Express Chipset Display Bundling HP LED 15,6' Memory 2 GB DDR3 Hard Drive 500GB Serial ATA, 7200RPM Optical Drive HP SuperMulti DVD Drive Storage Controller Serial ATA Keyboard HP USB Standard Keyboard Audio Type Integrated High Definition Audio, 5.1 Surround Sound Ready Networking Fast Ethernet Network Speed 10 / 100 Mbps Card Reader 6",
    price: 5750000,
    pic: DesktopPC1,
  },
  {
    id: 3,
    title: "Desktop PC",
    Subtitle: "HP ProDesk 490 G2 Microtower PC L0J14PA",
    desc: "Desktop PC HP PRODESK 490 G2 MT [L0J14PA] murah, bergaransi resmi dan online di Jakarta, Indonesia. Dengan sistem pembayaran cash, kartu kredit, cicilan dan COD. Berbagai macam Desktop dapat Anda temukan di distributor resmi HP Dimensidata.com.Memenuhi kebutuhan Anda dan anggaran Anda dengan desktop bisnis terjangkau siap untuk ekspansi dan upgrade dengan opsional displays. HP PRODESK 490 G2 MT menyediakan akses mudah ke komponen dalam chassis dan koneksi opsional untuk mendukung hingga tig",
    price: 7100000,
    pic: DesktopPC2,
  },
  {
    id: 4,
    title: "Desktop PC",
    Subtitle: "HP ProDesk 490 G2 Microtower PC L0J14PA",
    desc: "Desktop PC HP PRODESK 490 G2 MT [L0J14PA] murah, bergaransi resmi dan online di Jakarta, Indonesia. Dengan sistem pembayaran cash, kartu kredit, cicilan dan COD. Berbagai macam Desktop dapat Anda temukan di distributor resmi HP Dimensidata.com.Memenuhi kebutuhan Anda dan anggaran Anda dengan desktop bisnis terjangkau siap untuk ekspansi dan upgrade dengan opsional displays. HP PRODESK 490 G2 MT menyediakan akses mudah ke komponen dalam chassis dan koneksi opsional untuk mendukung hingga tig",
    price: 7100000,
    pic: DesktopPC3,
  },
  {
    id: 5,
    title: "Leptop",
    Subtitle: "Dell XPS 13 Core i3",
    desc: "Produk 11th Generation Intel Core i5 1135G7 8 MB Cache 4 Core up to 4 20 GHz 13 4 inch FHD 1920 x 1200 60 Hz anti glare non touch InfinityEdge sRGB 100 typical 500 nits wide viewing angle 8 GB LPDDR4x 4267 MHz memory onboard 512 GB M 2 2280 PCIe NVMe Gen3 x4 SSD Intel Iris Xe Graphics Windows 10 Pro 64 bit Microsoft Office Home and Student 2019 Widescreen HD 720p 2 25mm webcam McAfee LiveSafe 12 month Subscription Stereo speakers 2 5W x 2 4W peak professionally tuned with Waves MaxxAud",
    price: 9500000,
    pic: Leptop,
  },
  {
    id: 6,
    title: "Leptop",
    Subtitle: "HP Notebook 15-bw069ax 2DN93PA",
    desc: "HP 15 BW069AX merupakan laptop dengan layar 15 6 Inch beresolusi 1024 x 768 Laptop ini dibekali dengan sistem operasi Windows 10 prosesor AMD A10 9620P dan grafis AMD RADEON 530 2GB Laptop ini juga dilengkapi dengan 1 TB 5400 rpm SATA dan memori RAM 8GB",
    price: 6499000,
    pic: Leptop1,
  },
  {
    id: 7,
    title: "Leptop",
    Subtitle: "HP Pavilion x360 14-ba003tx 1XE30PA",
    desc: "HP Pavilion 14-ba003tx x360 Ci5-7200U - 8GBD4 - 1TB -GF940MX2GB - W10HSL - 2YR (357336164) Brand Hewlett-Packard Type Computers & Laptops Laptops",
    price: 9900000,
    pic: Leptop2,
  },
  {
    id: 8,
    title: "Periferal",
    Subtitle: "LG LED Monitor 18.5 Inch 19M38A-B",
    desc: "LG memperkenalkan sebuah monitor LED berukuran 18 5 inch Kabarnya monitor ini sudah diberikan perbaikan algoritma sehingga warna yang terpancar dari monitor ini lebih bervariasi Selain itu untuk menjaga kesehatan mata dan kenyamanan saat berada didepan layar monitor maka LG19M38A dibekali fitur Flicker Safe Meskipun ukuran layar ini tidak terlalu besar solusinya LG menyediakan fitur Split Screen untuk memaksimalkan ruang kerja Anda Selanjutnya fitur bawaan Monitor ini yaitu On Screen Control",
    price: 848000,
    pic: Monitor,
  },
  {
    id: 9,
    title: "Periferal",
    Subtitle: "Logitech Wireless Combo Keyboard + Mouse MK220",
    desc: "Logitech Wireless Desktop MK220 Combo Keyboard Mouse Wireless harga 1 item Kebutuhan SistemWindows XP Windows Vista atau Windows 7 Windows 8port USB Informasi GaransiGaransi terbatas hardware 1 tahun Isi KemasanKeyboard K220 Mouse M150 penerima sinyal USB2 baterai AAA keyboard dan 2 baterai AA mouse Dokumentasi pengguna",
    price: 210000,
    pic: Keyboard,
  },
  {
    id: 10,
    title: "Periferal",
    Subtitle: "Canon PIXMA MP287",
    desc: "Tingkatkan pilihan kreativitas Anda dengan mencetak momen favorit Anda menggunakan Full HD Movie Print. Sekarang Anda dapat menangkap frame individual dari film HD. Anda memotret dengan kamera digital Canon Anda. Dan Anda bisa menyempurnakan cetakan Anda dengan teknologi koreksi gambar Canon yang canggih",
    price: 725000,
    pic: Printer,
  },
  {
    id: 11,
    title: "Komponen PC",
    Subtitle: "Asus Phoenix GeForce GTX 1050 2GB Graphic Card",
    desc: "ASUS VGA GTX1050 Phoenix (PH) 2GB DDR5 128bit (1 Fan) (670920152) Brand Asus Type Computers & Laptops Computer Components",
    price: 2025900,
    pic: VGA,
  },
  {
    id: 12,
    title: "Komponen PC",
    Subtitle: "Asus ROG Strix GeForce GTX 1060 OC 6GB Graphic Card",
    desc: "ASUS Strix GeForce GTX 1060 OC edition 6GB GDDR5 STRIX-GTX1060-O6G Paduan komponen premium pada kartu grafis ini memberikan performa yang optimal pada tampilan visual grafis Anda. Anda juga dapat menggunakan port HDMI untuk menikmati fitur virtual reality (VR) ready dengan mudah. Kini pengaturan suhu GPU bahkan dapat dikendalikan pada tingkatan tertentu untuk tetap menjaga performa yang tahan lama. Anda juga dapat mengatur kendali sistem dan fitur dengan lebih praktis melalui kendali Gaming",
    price: 7998000,
    pic: VGA1,
  },
  {
    id: 13,
    title: "Komponen PC",
    Subtitle: "Gigabyte Motherboard AORUS X370-Gaming 5",
    desc: "GIGABYTE GA-AX370-GAMING 5 (666194038) Brand Amd Type Computers & Laptops Computer Components",
    price: 2150000,
    pic: MotherBoard,
  },
];
